import type { Metadata } from "next";
import { LegalPage } from "@/components/shared/LegalPage";
import Link from "next/link";
import { COMPANY } from "@/lib/company";
import { createPageMetadata } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata({
  title: "Terms of service",
  description: `Terms governing use of ${COMPANY.product}, payments, AI-generated content, and user responsibilities. ${COMPANY.name}.`,
  path: "/terms",
  ogType: "article",
});

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of service"
      description={`Effective date: ${COMPANY.effectiveDate} · ${COMPANY.product} by ${COMPANY.name}`}
    >
      <h2 className="text-base font-semibold text-ink">Acceptance of terms</h2>
      <p>
        By using {COMPANY.product} you agree to these Terms of Service. If you do
        not agree, do not use the platform.
      </p>

      <h2 className="text-base font-semibold text-ink">About the service</h2>
      <p>
        {COMPANY.product} provides AI-powered resume generation. You provide raw
        input about your education, skills, and experience. Our system generates a
        structured resume and delivers it as a PDF. The service is available to
        individuals aged 18 and above, or students with parental consent.
      </p>

      <h2 className="text-base font-semibold text-ink">Payment terms</h2>
      <ul className="list-disc space-y-2 pl-5">
        <li>Service is priced at ₹50 per resume generation</li>
        <li>Payment is processed securely via Razorpay</li>
        <li>Payment must be completed before generation begins</li>
        <li>All prices are in Indian Rupees and inclusive of applicable taxes</li>
      </ul>

      <h2 className="text-base font-semibold text-ink">Your responsibilities</h2>
      <p>By using {COMPANY.product} you agree that:</p>
      <ul className="list-disc space-y-2 pl-5">
        <li>
          All information you provide is accurate and truthful to the best of your
          knowledge
        </li>
        <li>
          You will not submit false, fabricated, or misleading information about
          your qualifications, experience, or skills
        </li>
        <li>You are the rightful owner of all content you submit</li>
        <li>
          You will not use the platform to generate resumes with false credentials
          for fraudulent applications
        </li>
        <li>
          You understand that AI-generated content must be reviewed and edited by
          you before submission to employers
        </li>
        <li>
          You will not attempt to reverse engineer, scrape, or misuse the platform
        </li>
      </ul>

      <h2 className="text-base font-semibold text-ink">AI-generated content</h2>
      <p>
        Resume content generated by {COMPANY.product} is produced by an AI system
        based on the input you provide. {COMPANY.name}:
      </p>
      <ul className="list-disc space-y-2 pl-5">
        <li>Does not guarantee that generated content will result in job interviews or offers</li>
        <li>Does not guarantee ATS compatibility with every employer system</li>
        <li>Is not responsible for decisions made by employers based on your resume</li>
        <li>Recommends reviewing and editing all AI-generated content before use</li>
      </ul>

      <h2 className="text-base font-semibold text-ink">Resume deletion</h2>
      <p>
        All generated resumes and associated data are permanently deleted from our
        systems within 24 hours of creation. You are solely responsible for
        downloading and saving your PDF within this window. {COMPANY.name} is not
        liable for loss of data after the 24-hour period.
      </p>

      <h2 className="text-base font-semibold text-ink">Intellectual property</h2>
      <p>
        The resume content generated from your input belongs to you. The{" "}
        {COMPANY.product} platform, AI prompt system, LaTeX templates, and
        underlying technology are the intellectual property of {COMPANY.name} and
        may not be copied, replicated, or reverse engineered.
      </p>

      <h2 className="text-base font-semibold text-ink">Limitation of liability</h2>
      <p>{COMPANY.name} shall not be liable for:</p>
      <ul className="list-disc space-y-2 pl-5">
        <li>Any indirect, incidental, or consequential damages</li>
        <li>Loss of employment opportunities or career outcomes</li>
        <li>Errors in AI-generated content that you did not review</li>
        <li>Data loss after the 24-hour deletion window</li>
        <li>Service interruptions due to third-party dependencies</li>
      </ul>
      <p>
        Our total liability to you shall not exceed the amount you paid for the
        specific transaction in question.
      </p>

      <h2 className="text-base font-semibold text-ink">Service availability</h2>
      <p>
        We aim for maximum uptime but do not guarantee uninterrupted service.
        Maintenance, updates, or third-party failures may cause temporary
        unavailability. In such cases, if generation fails after payment, a full
        refund will be issued per our{" "}
        <Link href="/refund-policy" className="text-ink underline">
          Refund Policy
        </Link>
        .
      </p>

      <h2 className="text-base font-semibold text-ink">Governing law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes shall be
        subject to the exclusive jurisdiction of courts in Ongole, Andhra Pradesh,
        India.
      </p>

      <h2 className="text-base font-semibold text-ink">Changes to terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the platform
        after changes constitutes acceptance of the updated Terms. Material changes
        will be communicated via email.
      </p>

      <h2 className="text-base font-semibold text-ink">Contact</h2>
      <p>{COMPANY.name}</p>
      <p>{COMPANY.location}</p>
      <p>CIN: {COMPANY.cin}</p>
      <p>
        <a href={`mailto:${COMPANY.email}`} className="text-ink underline">
          {COMPANY.email}
        </a>
      </p>
      <p>
        <a
          href={COMPANY.website}
          className="text-ink underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          sarwagyna.com
        </a>
      </p>
    </LegalPage>
  );
}
